export const ACTIVITY_LIST = Object.freeze({
  0: 'Rock Climbing',
  1: 'Cruise',
  3: 'Fishing',
  4: 'Potluck',
  5: 'Board Game',
  6: 'Trivia',
  7: 'Improv Workshop',
  8: 'Karaoke Night',
  9: 'Go-Kart Racing',
  10: 'Volunteering',
  11: 'Watching Movie',
  12: 'Escape Room',
  13: 'Laser Tag',
  14: 'Murder Mystery',
  15: 'Kayaking',
  16: 'Trampoline',
  17: 'Canoeing',
  18: 'Painting Class',
  19: 'Cooking Class',
  20: 'Visiting Museum',
  21: 'Sports Game',
  22: 'Picnic',
  23: 'Hiking',
  24: 'Hip-hop Dancing Class',
  25: 'Theater Show',
  26: 'Yoga',
  27: 'Happy Hour',
  28: 'Poker',
  29: 'Wine Tasting',
  30: 'Chess',
  31: 'Video Games',
  32: 'Arcade Games',
  33: 'Group Bike Ride',
});
